name: hello

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greet to user
        run: echo "Hello Tushar"
      - name: greet my user
        run: echo "Hello $USER"
  
  
